version: '3'
services: 
  api:
    build: .
    ports:
      - 8000:8000
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres   #아래에 있는 postgres 이미지의 ip를 사용하겠다는 의미
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=kjhyym415*
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCSES_TOKEN_EXPIRE_TIME=60  
    
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWOR=kjhyym415*
      - POSTGRES_DB=fastapi

    # container가 죽을 때마다 데이터가 사라지지 않게 volumn 설정
    volumes:
      - postgres-db:/var/lib/postgresql/data
  
volumes:
  postgres-db:
